dart_code_metrics:
  rules:
    - avoid-self-compare

analyzer:
  exclude: [ build/**, plugins/** ]
  language:
    strict-casts: false
    strict-raw-types: false
  errors:
    unused_import: error              # 禁止存在未使用的 import
    unused_local_variable: error      # 禁止声明但未使用的局部变量
    unused_element: error             # 禁止存在未使用的类 / 方法 / 函数 / 构造函数
    unused_field: error               # 禁止声明但从未使用的类成员变量（字段）
# 编码规范
linter:
  rules:
    - avoid_relative_lib_imports            # 避免相对路径导入
    - avoid_unused_constructor_parameters   # 避免未使用的构造函数参数
    - avoid_empty_else                      # 避免空else
    - cancel_subscriptions                  # 取消订阅
    - avoid_final_parameters                # 避免 final 参数
    - package_names                         # 必须是小写 + 下划线
    - file_names                            # 必须是小写 + 下划线
    - use_named_constants                   # 使用预定义的命名常量
