dart_code_metrics:
  rules:
    - avoid-self-compare

analyzer:
  exclude: [ build/**, plugins/** ]
  language:
    strict-casts: false
    strict-raw-types: false
  errors:
    unused_import: error
    unused_local_variable: error
    unused_element: error

# 编码规范
linter:
  rules:
    - avoid_relative_lib_imports            # 避免相对路径导入
    - avoid_unused_constructor_parameters   # 避免未使用的构造函数参数
    - avoid_empty_else                      # 避免空else
    - cancel_subscriptions                  # 取消订阅
    - avoid_final_parameters                # 避免 final 参数
    - package_names                         # lowercase_with_underscores
    - file_names                            # lowercase_with_underscores
    - use_named_constants                   # 使用预定义的命名常量
